### ISSUE TITLE
Import annotations on external terms

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/GECKO#12]
After we create an `extract.py` script in our ontology gizmos (https://github.com/ontodev/gizmos/issues/13), we should use this to import all annotations on external terms. Right now, the definitions for these terms are just included in our template, but it would be better to extract them from their source ontologies.

Perhaps we want to move all external terms to an `external.tsv` template instead, as well.

**Comment by matentzn** [comment]
especially synonyms would be very very helpful improving the matching!
