### ISSUE TITLE
Create an official release of GECKO

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/GECKO#15]
After we finalize the NTRs from EnVO (https://github.com/EnvironmentOntology/envo/issues/1008) and EUPATH (or OGMS https://github.com/OGMS/ogms/issues/146), I think we should move forward with an official GECKO release.

@mcourtot what do you think?

**Comment by mcourtot** [comment]
That'd be great! I have asked Vivian from CINECA to look at the model extensions (NTRs) too, so hopefully good to go.

**Comment by beckyjackson** [comment]
We no longer need the OGMS term, but I just left a comment on the EnVO issue. If we can't get the EnVO term in this week, I'll add it to GECKO so we can make our release. We can always deprecate it later if EnVO adds it.
