### ISSUE TITLE
View over GECKO

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#21]
Wondering if it'd be easy to generate some 'view' of GECKO. For example, I'm trying to show GECKO as per the IHCC browser, but under "phenotypic data' in the browser there is just yes or no, while I think we have diseases etc as well.

I don't know which format would be best - a csv or OWL or some diagram? I guess a CSV would work well as it can be ordered by higher category, though a OWL could be loaded in Protege for screenshoting?

The context is increasing the number of attributes to represent cohorts in phenopackets, and I'd like to make a case that we should at first pass include the IHCC high level categories, while providing a view of their subclasses.

If it's too painful please ignore, just in case you have an easy to implement idea.

**Comment by beckyjackson** [comment]
I'd be happy to generate a diagram of the OWL or a CSV file, but I'm not sure I quite understand what it is you're asking for. Do you want to see a full overview of the entire GECKO structure?

**Comment by beckyjackson** [comment]
We have a diagram in the README and a CSV from #24 - I think this can be closed but please re-open if you need anything else for this!
