### ISSUE TITLE
Export GECKO IHCC as CSV

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#23]
Hi - would it please be possible to add a CSV export to the makefile? Contributors like handling the model in a spreadsheet, so the ability to load an up to date version in sync with the OWL would be very useful to make sure they are using the right version of the model (instead of the original CINECA WP3 spreadsheet)

**Comment by jamesaoverton** [comment]
Sure, we can generate a `views/gecko.csv`. @beckyjackson will do a first pass and you can let us know if it's missing anything important.

**Comment by beckyjackson** [comment]
@mcourtot should this be GECKO OBO-version or IHCC-version? Or would you like both?

**Comment by mcourtot** [comment]
Ihcc would be great - this is to 'replace' the existing WP3 spreadsheet Thanks!
