### ISSUE TITLE
lifestyle classes label

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#26]
https://registry.ihccglobal.app/ontologies/gecko/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGECKO_0000067&viewMode=All&siblings=true

Should subclasses of lifestyle be called "xxx history" eg 'drug history'? It seems a little bit confusing to be just labeled 'drugs'

**Comment by beckyjackson** [comment]
That would be an easy fix! I was just going based off the original CINECA data model which just used the label "drugs", but I agree that it makes more sense to call them "X history".

Would you like me to move forward and rename these terms?

**Comment by mcourtot** [comment]
Sounds good, thanks!
