### ISSUE TITLE
Organizing children of diseases

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/GECKO#29]
Related to #28 - we are adding more disease terms, and probably will continue to do so. Currently, all terms end up directly under "diseases" in the IHCC view. This is starting to look a bit messy, as some are diseases of anatomical system and could be categorized as such (maybe "disease of anatomy" and "other diseases" for now... I'm not sure)

I'm not sure how this would work for the browser, as all other categories are just flat lists. But I worry that the list for diseases will get too long and be hard to navigate.

**Comment by beckyjackson** [comment]
@rosibaj could you provide some feedback/ideas for this organization for the browser?

**Comment by beckyjackson** [comment]
We will add these organizing nodes to GECKO, but the IHCC view will still be a flat list.

**Comment by rosibaj** [comment]
@beckyjackson UI updates as you have suggested are possible, but need to be prioritized with other feature development based on the next design/development cycle; ill note this and connect with Christina and Melanie on that.

**Comment by beckyjackson** [comment]
Thanks @rosibaj - the changes we are making to the GECKO file now will not impact the JSON until we make changes to the IHCC view & the code to generate the JSON.
