### ISSUE TITLE
Rename children of diseases

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/GECKO#33]
Right now the children of "diseases" have very ambiguous names, such as "circulatory system". When doing the mappings and looking at a list of the terms, I would not know that this is a reference to diseases of the circulatory system.

I think that we should rename these to be "X disease", e.g. "circulatory system disease".

@mcourtot would this be OK?

**Comment by mcourtot** [comment]
This would actually be way better.

**Comment by beckyjackson** [comment]
@mcourtot While we're doing this update to disease labels, I think it would be nice to rename "administration" and "prescription" to "drug administration" and "drug prescription" as well to be less ambiguous.
