### ISSUE TITLE
GECKO PURLs - dates and releases

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#46]
Maybe related to #15 

I was showing https://registry.ihccglobal.app/ontologies/gecko to a collaborator yesterday and discussing versioning, but the dated PURL returns a 404 and there is nothing under the /releases directory

**Comment by jamesaoverton** [comment]
We just haven't created any "releases" of GECKO yet. We can do so at any time, and we could tag older versions as releases. I guess they don't have to be "official".

Would you like a release of the current version? Would you like any pervious versions marked as releases?

**Comment by mcourtot** [comment]
Could we do one before DAC and then one for the new DAC demo? We can mark them as draft, but it'd be good to have tags so we can diff etc.

**Comment by jamesaoverton** [comment]
I just created a release for 2020-12-03. @beckyjackson Please make another release this week, before the demo.
