### ISSUE TITLE
mis formatting in csv export?

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/GECKO#7]
https://github.com/IHCC-cohorts/GECKO/blob/master/src/ontology/templates/gecko.tsv

"We can make this file beautiful and searchable if this error is corrected: It looks like row 47 should actually have 12 columns, instead of 10. in line 46."

**Comment by mcourtot** [comment]
https://github.com/IHCC-cohorts/GECKO/blob/master/src/ontology/templates/gecko.tsv

line 2 duplicates the headers and should be removed

**Comment by jamesaoverton** [comment]
This is the source file, not an export, and the second row tells ROBOT how to turn the rows into OWL format.
